title: West Malvern Churchyard
url: "https://www.westmalvernchurchyard.org.uk"

sass:
  style: compact
  sass_dir: _sass

plugins:
  - jekyll-datapage-generator
  - jekyll-sitemap

page_gen-dirs: false

page_gen:
  - data: graves
    name: id
    template: grave

exclude: ["west-malvern-memorials.sublime-project", "west-malvern-memorials.sublime-workspace" "README.md"]
