title: West Malvern Memorials
url: "https://www.westmalvernmemorials.org.uk"

sass:
  style: compact
  sass_dir: _sass

plugins:
  - jekyll-datapage-generator
  - jekyll-sitemap

page_gen-dirs: false

page_gen:
  - data: graves
    name: id
    template: grave
